repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: README.md
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-xml
      - id: check-case-conflict
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - '--max-line-length=150'
          - '--ignore=E203,W503'
